### ISSUE TITLE
GUI_1: Set up h file

### ISSUE THREAD

**Issue by MatheuBotha** [MatheuBotha/DragonBrain#2]
Create initial file hierarchy.

**Comment by RentonMcIntyre** [comment]
I have created an initial floating window GUI (to be separate from the rendering window, hopefully this will reduce complexity of overall project).

It has been created with Qt (using QtQuick, a designer that I'm not as familiar with as Qt's stock, but does do a better job in making more modern designs).

It currently has no functionality, but this should be simple to implement (simply grab selected data from the interface and push it where it needs to go).
More importantly, I am unsure if the design meets everybody's desires, since my UI desires are usually not extensive.
 I have uploaded some screenshots of the design to the GUI branch for those who can't get Qt setup quickly. This should give an idea of how it looks, although the sliding animation when switching tabs cannot be shown this way.

Thoughts?
